import { NextResponse } from "next/server";
import { seedEvents } from "@/lib/kv";
import { LifeEvent } from "@/lib/types";

// Rich seed data for demo/development — 36 events across weeks 11–14
const SEED_DATA: LifeEvent[] = [
  // ══════ WEEK 11 (Mar 28 – Apr 3) ══════
  {
    id: "w11-01",
    title: "AI Mid-Term CT",
    course: "CSE 3209",
    type: "CT",
    description: "Chapters 1-6: Search algorithms, CSPs, adversarial search, Bayesian networks. Bring calculator.",
    date: "2026-03-28",
    time: "09:00 AM",
    room: "Room 301",
    week: 11,
    resources: ["https://drive.google.com/ai-notes", "https://drive.google.com/ai-slides"],
  },
  {
    id: "w11-02",
    title: "Compiler Design Assignment 1",
    course: "CSE 3211",
    type: "Assignment",
    description: "Implement a lexical analyzer for a subset of C language. Submit source code + report.",
    date: "2026-03-28",
    submissionDate: "2026-04-02",
    time: "11:59 PM",
    week: 11,
    resources: ["https://craftinginterpreters.com"],
  },
  {
    id: "w11-03",
    title: "Mobile App UI Prototype",
    course: "CSE 3217",
    type: "Project",
    description: "Design and implement UI mockup for semester project. Must include at least 5 screens with navigation.",
    date: "2026-03-29",
    submissionDate: "2026-04-01",
    time: "11:59 PM",
    week: 11,
  },
  {
    id: "w11-04",
    title: "SE&PM Group Assignment",
    course: "CSE 3219",
    type: "Assignment",
    description: "Software Requirements Specification (SRS) document for your team project. IEEE format required.",
    date: "2026-03-29",
    submissionDate: "2026-04-03",
    time: "11:59 PM",
    week: 11,
  },
  {
    id: "w11-05",
    title: "SDP Sprint 3 Review",
    course: "CSE 3200",
    type: "Presentation",
    description: "Demo Sprint 3 deliverables. Show working features, updated Jira board. Each member must speak.",
    date: "2026-03-30",
    time: "02:00 PM",
    room: "Lab 201",
    week: 11,
  },
  {
    id: "w11-06",
    title: "Technical Writing - Draft 1",
    course: "CSE 3230",
    type: "Assignment",
    description: "First draft of technical report. Minimum 3000 words. APA citation format.",
    date: "2026-03-31",
    submissionDate: "2026-04-02",
    time: "11:59 PM",
    week: 11,
  },
  {
    id: "w11-07",
    title: "Engineers & Society Quiz 1",
    course: "HUM 3247",
    type: "Quiz",
    description: "Online quiz on chapters 1-4. Open for 30 minutes. MCQ + short answers.",
    date: "2026-04-01",
    time: "10:00 AM",
    week: 11,
  },
  {
    id: "w11-08",
    title: "AI Lab Test 1",
    course: "CSE 3210",
    type: "Lab Test",
    description: "Implement BFS/DFS and A* search on given graph. Viva after code submission.",
    date: "2026-04-02",
    time: "02:00 PM",
    room: "Lab 301",
    week: 11,
  },
  {
    id: "w11-09",
    title: "Compiler Lab - Lexer Demo",
    course: "CSE 3212",
    type: "Lab Test",
    description: "Demonstrate your lexical analyzer implementation. Individual viva on token recognition.",
    date: "2026-04-03",
    time: "10:00 AM",
    room: "Lab 302",
    week: 11,
  },

  // ══════ WEEK 12 (Apr 4 – Apr 10) ══════
  {
    id: "w12-01",
    title: "Compiler Design CT-1",
    course: "CSE 3211",
    type: "CT",
    description: "Topics: Regular expressions, finite automata (DFA/NFA), context-free grammars, LL parsing.",
    date: "2026-04-04",
    time: "09:00 AM",
    room: "Room 302",
    week: 12,
  },
  {
    id: "w12-02",
    title: "Mobile App Lab Test 1",
    course: "CSE 3218",
    type: "Lab Test",
    description: "Build a Flutter app with navigation, state management, and API call in 2 hours.",
    date: "2026-04-05",
    time: "02:00 PM",
    room: "Lab 303",
    week: 12,
  },
  {
    id: "w12-03",
    title: "SE Lab - Testing Demo",
    course: "CSE 3220",
    type: "Lab Test",
    description: "Unit testing demo for your SE project. Must have 80%+ code coverage. JUnit/pytest accepted.",
    date: "2026-04-06",
    time: "10:00 AM",
    room: "Lab 201",
    week: 12,
  },
  {
    id: "w12-04",
    title: "AI Assignment - Bayesian Networks",
    course: "CSE 3209",
    type: "Assignment",
    description: "Implement a Bayesian network for medical diagnosis. Python + pgmpy library.",
    date: "2026-04-06",
    submissionDate: "2026-04-10",
    time: "11:59 PM",
    week: 12,
  },
  {
    id: "w12-05",
    title: "SDP Sprint 4 Planning",
    course: "CSE 3200",
    type: "Seminar",
    description: "Sprint 4 planning meeting. Define user stories, assign tasks, estimate story points.",
    date: "2026-04-07",
    time: "03:00 PM",
    room: "Room 201",
    week: 12,
  },
  {
    id: "w12-06",
    title: "Mobile App Mid-Progress Review",
    course: "CSE 3217",
    type: "Presentation",
    description: "Show 50% completion of mobile app project. Backend integration required.",
    date: "2026-04-08",
    time: "11:00 AM",
    room: "Room 305",
    week: 12,
  },
  {
    id: "w12-07",
    title: "Technical Writing - Peer Review",
    course: "CSE 3230",
    type: "Assignment",
    description: "Review 2 classmates' drafts using the provided rubric. Submit feedback document.",
    date: "2026-04-09",
    submissionDate: "2026-04-10",
    time: "11:59 PM",
    week: 12,
  },
  {
    id: "w12-08",
    title: "Engineers & Society Presentation",
    course: "HUM 3247",
    type: "Presentation",
    description: "Group presentation on 'Ethics in AI Development'. 15 min + 5 min Q&A. Slides required.",
    date: "2026-04-10",
    time: "10:00 AM",
    room: "Room 401",
    week: 12,
  },

  // ══════ WEEK 13 (Apr 11 – Apr 17) ══════
  {
    id: "w13-01",
    title: "SE&PM CT-1",
    course: "CSE 3219",
    type: "CT",
    description: "Topics: SDLC models, requirements engineering, UML diagrams, project estimation techniques.",
    date: "2026-04-11",
    time: "09:00 AM",
    room: "Room 301",
    week: 13,
  },
  {
    id: "w13-02",
    title: "Mobile App CT-1",
    course: "CSE 3217",
    type: "CT",
    description: "Flutter widgets, state management, navigation, HTTP/REST concepts, local storage.",
    date: "2026-04-12",
    time: "09:00 AM",
    room: "Room 302",
    week: 13,
  },
  {
    id: "w13-03",
    title: "Compiler Lab Test - Parser",
    course: "CSE 3212",
    type: "Lab Test",
    description: "Implement recursive descent parser for given grammar. Must handle error recovery.",
    date: "2026-04-13",
    time: "02:00 PM",
    room: "Lab 302",
    week: 13,
  },
  {
    id: "w13-04",
    title: "AI Project Proposal",
    course: "CSE 3209",
    type: "Project",
    description: "Submit AI project proposal: problem statement, dataset, methodology, timeline. Max 5 pages.",
    date: "2026-04-13",
    submissionDate: "2026-04-15",
    time: "11:59 PM",
    week: 13,
  },
  {
    id: "w13-05",
    title: "SDP Code Review",
    course: "CSE 3200",
    type: "Seminar",
    description: "Cross-team code review session. Review another team's codebase for quality and design patterns.",
    date: "2026-04-14",
    time: "02:00 PM",
    room: "Lab 201",
    week: 13,
  },
  {
    id: "w13-06",
    title: "Compiler Assignment 2",
    course: "CSE 3211",
    type: "Assignment",
    description: "Build a syntax-directed translator for arithmetic expressions. Must generate three-address code.",
    date: "2026-04-14",
    submissionDate: "2026-04-17",
    time: "11:59 PM",
    week: 13,
  },
  {
    id: "w13-07",
    title: "Engineers & Society Essay",
    course: "HUM 3247",
    type: "Assignment",
    description: "2000-word essay on 'Technology and Social Responsibility'. Individual submission.",
    date: "2026-04-15",
    submissionDate: "2026-04-17",
    time: "11:59 PM",
    week: 13,
  },
  {
    id: "w13-08",
    title: "SE Lab - Integration Testing",
    course: "CSE 3220",
    type: "Lab Test",
    description: "Integration test demo. Show API endpoint testing with Postman/Insomnia + CI pipeline.",
    date: "2026-04-16",
    time: "10:00 AM",
    room: "Lab 201",
    week: 13,
  },
  {
    id: "w13-09",
    title: "Mobile Lab - API Integration",
    course: "CSE 3218",
    type: "Lab Test",
    description: "Connect Flutter app to REST API. CRUD operations with error handling and loading states.",
    date: "2026-04-17",
    time: "02:00 PM",
    room: "Lab 303",
    week: 13,
  },

  // ══════ WEEK 14 (Apr 18 – Apr 24) ══════
  {
    id: "w14-01",
    title: "AI CT-2",
    course: "CSE 3209",
    type: "CT",
    description: "Chapters 7-12: Machine learning basics, decision trees, neural networks, NLP fundamentals.",
    date: "2026-04-18",
    time: "09:00 AM",
    room: "Room 301",
    week: 14,
  },
  {
    id: "w14-02",
    title: "SE Lab Final Demo",
    course: "CSE 3220",
    type: "Lab Test",
    description: "Final project demo. Complete system with documentation. All members must present their modules.",
    date: "2026-04-19",
    time: "10:00 AM",
    room: "Lab 201",
    week: 14,
  },
  {
    id: "w14-03",
    title: "SDP Final Presentation",
    course: "CSE 3200",
    type: "Presentation",
    description: "Final sprint demo + retrospective. Complete working product. Client feedback session.",
    date: "2026-04-20",
    time: "02:00 PM",
    room: "Room 201",
    week: 14,
    resources: ["https://drive.google.com/sdp-rubric"],
  },
  {
    id: "w14-04",
    title: "Technical Writing Final Paper",
    course: "CSE 3230",
    type: "Assignment",
    description: "Final version of technical report incorporating all peer feedback. Plagiarism check required.",
    date: "2026-04-20",
    submissionDate: "2026-04-22",
    time: "11:59 PM",
    week: 14,
  },
  {
    id: "w14-05",
    title: "Compiler Design CT-2",
    course: "CSE 3211",
    type: "CT",
    description: "LR parsing, syntax-directed translation, intermediate code generation, code optimization basics.",
    date: "2026-04-21",
    time: "09:00 AM",
    room: "Room 302",
    week: 14,
  },
  {
    id: "w14-06",
    title: "Mobile App Final Submission",
    course: "CSE 3217",
    type: "Project",
    description: "Complete mobile app with all features. APK + source code + user manual. Play Store ready.",
    date: "2026-04-21",
    submissionDate: "2026-04-23",
    time: "11:59 PM",
    week: 14,
  },
  {
    id: "w14-07",
    title: "AI Lab Final Test",
    course: "CSE 3210",
    type: "Lab Test",
    description: "Implement a complete ML pipeline: data preprocessing, model training, evaluation. Viva on theory.",
    date: "2026-04-22",
    time: "02:00 PM",
    room: "Lab 301",
    week: 14,
  },
  {
    id: "w14-08",
    title: "Engineers & Society Final Quiz",
    course: "HUM 3247",
    type: "Quiz",
    description: "Comprehensive quiz covering all chapters. MCQ + essay question. 45 minutes.",
    date: "2026-04-23",
    time: "10:00 AM",
    week: 14,
  },
  {
    id: "w14-09",
    title: "SE&PM Assignment - Final Report",
    course: "CSE 3219",
    type: "Assignment",
    description: "Complete project management report: Gantt chart, risk analysis, cost estimation, lessons learned.",
    date: "2026-04-23",
    submissionDate: "2026-04-24",
    time: "11:59 PM",
    week: 14,
  },
  {
    id: "w14-10",
    title: "Compiler Lab Final - Code Gen",
    course: "CSE 3212",
    type: "Lab Test",
    description: "Implement intermediate code generator. Must handle assignments, conditionals, and loops.",
    date: "2026-04-24",
    time: "10:00 AM",
    room: "Lab 302",
    week: 14,
  },
];

export async function POST() {
  try {
    await seedEvents(SEED_DATA);
    return NextResponse.json({
      success: true,
      message: `Seeded ${SEED_DATA.length} events`,
    });
  } catch {
    return NextResponse.json(
      { error: "Failed to seed data" },
      { status: 500 }
    );
  }
}
